"""create stations and requests

Revision ID: 643e85220a4a
Revises: 
Create Date: 2026-09-19 17:09:53.318258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '643e85220a4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('requests',
    sa.Column('id', app.models.types.UUIDBinary(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=16), nullable=False),
    sa.Column('access_token', sa.CHAR(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_index(op.f('ix_requests_expires_at'), 'requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_requests_external_id'), 'requests', ['external_id'], unique=False)
    op.create_index(op.f('ix_requests_station_id'), 'requests', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_station_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_external_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_expires_at'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('stations')
    # ### end Alembic commands ###
