"""create messages

Revision ID: 9825b3fa429a
Revises: a60df9c43cfd
Create Date: 2026-09-19 18:03:34.572207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = '9825b3fa429a'
down_revision: Union[str, Sequence[str], None] = 'a60df9c43cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', app.models.types.UUIDBinary(length=16), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_request_sent', 'messages', ['request_id', 'sent_at'], unique=False)
    op.create_index('ix_messages_unread_scan', 'messages', ['read_at', 'notified_at', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_unread_scan', table_name='messages')
    op.drop_index('ix_messages_request_sent', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
