"""create questionnaire_answers

Revision ID: a60df9c43cfd
Revises: 643e85220a4a
Create Date: 2026-09-19 17:56:45.056540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# revision identifiers, used by Alembic.
revision: str = 'a60df9c43cfd'
down_revision: Union[str, Sequence[str], None] = '643e85220a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', app.models.types.UUIDBinary(length=16), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answers_request_field', 'questionnaire_answers', ['request_id', 'field_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_answers_request_field', table_name='questionnaire_answers')
    op.drop_table('questionnaire_answers')
    # ### end Alembic commands ###
